-- Recommendations table: stores actionable insights generated by analysis.

create table public.recommendations (
  id uuid default gen_random_uuid() primary key,
  system_id uuid references public.solar_systems on delete cascade not null,
  type text not null check (type in ('cleaning', 'shade_check', 'degradation', 'general')),
  severity text not null check (severity in ('info', 'warning', 'critical')),
  title text not null,
  message text not null,
  metadata jsonb not null default '{}',
  status text not null default 'active' check (status in ('active', 'dismissed', 'resolved')),
  created_at timestamptz default now(),
  status_changed_at timestamptz,
  analysis_context jsonb not null default '{}'
);

-- Enable RLS
alter table public.recommendations enable row level security;

-- Users can read recommendations for their own systems
create policy "Users can read own recommendations"
  on public.recommendations for select using (
    exists (
      select 1 from public.solar_systems
      where solar_systems.id = recommendations.system_id
        and solar_systems.user_id = auth.uid()
    )
  );

-- Users can insert recommendations for their own systems
create policy "Users can insert own recommendations"
  on public.recommendations for insert with check (
    exists (
      select 1 from public.solar_systems
      where solar_systems.id = recommendations.system_id
        and solar_systems.user_id = auth.uid()
    )
  );

-- Users can update (dismiss/resolve) their own recommendations
create policy "Users can update own recommendations"
  on public.recommendations for update using (
    exists (
      select 1 from public.solar_systems
      where solar_systems.id = recommendations.system_id
        and solar_systems.user_id = auth.uid()
    )
  );

-- Indexes
create index idx_recommendations_system_id on public.recommendations (system_id);
create index idx_recommendations_active on public.recommendations (system_id, status) where status = 'active';
